---
apiVersion: v1
kind: Service
metadata:
        name: result-service
        labels:
                app: demo-voting-app
spec:
        type: LoadBalancer
        ports:
                - targetPort: 80
                  port: 80
        selector:
                matchLabels:
                        name: result-app-pod
                        app: demo-voting-app
