---
apiVersion: v1
kind: Service
metadata:
        name: redis-service
spec:
        type: LoadBalancer
        ports:
                - targetPort: 80 
                  port: 80
        selector:
                name: voting-app-pod
                app: demo-voting-app

