---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: worker-app-deploy
        labels:
                app: demo-voting-app
spec:
        replicas: 2
        selector:
                matchLabel:
                        name: worker-app-pod
                        app: demo-voting-app
        template:
                metadata:
                        name: worker-app-pod
                        label:
                                name: worker-app-pod
                                app: demo-voting-app
                spec:
                        container:
                                - name: worker
                                  image: dockersamples/examplevotingapp_worker

